version: '2'
services:
  db:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:rw
    environment:
      username: postgres
      password: postgres
      pool: 5
    ports:
      - "5432:5432"
  web:
    build: ./server
    working_dir: /var/www/app
    ports:
    - "5000:5000"
    volumes:
    - ./server:/var/www/app:rw
    depends_on:
    - db
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client/:/usr/src/app'
    ports:
      - '3000:3000'
    depends_on:
    - web
    environment:
      - NODE_ENV=development
